"""init

Revision ID: ffd63e3c2ef4
Revises: 
Create Date: 2024-02-19 11:33:25.041737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffd63e3c2ef4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("name", sa.Text(), server_default="", nullable=False),
        sa.Column("inn", sa.String(length=12), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("inn"),
    )
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("guid_pr", sa.String(length=36), nullable=False),
        sa.Column("guid_bp", sa.String(length=36), server_default="", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guid_pr"),
    )
    op.create_table(
        "customer_products",
        sa.Column("name", sa.Text(), server_default="", nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("customer_products")
    op.drop_table("products")
    op.drop_table("customers")
    # ### end Alembic commands ###
