"""Create Customer products

Revision ID: df7a9c8f7b8f
Revises: 3f6df480beb4
Create Date: 2024-02-16 12:10:05.927263

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df7a9c8f7b8f"
down_revision: Union[str, None] = "3f6df480beb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_products",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("customer_products")
    # ### end Alembic commands ###
